apiVersion: v1
kind: Service
metadata:  
  name: todo-app-nodeport-service
spec:
  selector:    
    app: todo-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31004
    protocol: TCP
